spring:
  profiles:
    active: local

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

app:
  jwt-service: homeplant
  jwt-expiration-in-ms: 2592000000 # 30일 1000 * 60 * 60 * 24 * 30

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: app-us-rds.conomzfuhb5p.ap-northeast-2.rds.amazonaws.com
    username: root
    password: appus1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate