spring:
  profiles:
    active: local

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:

    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    display-request-duration: true
    tags-sorter: alpha
    groups-order: asc

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

aws:
  sns:
    access_key: AKIA5OKCUASBU4JCPYXC
    secret_key: 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

app:
  jwt-secret: homeplant!
  jwt-expiration-in-ms: 2592000000 # 30일 1000 * 60 * 60 * 24 * 30

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://app-us-rds.conomzfuhb5p.ap-northeast-2.rds.amazonaws.com:3306/appus
    username: homeplant
    password: appus

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate


aws:
  sns:
    access_key: AKIA5OKCUASBU4JCPYXC
    secret_key: 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

app:
  jwt-secret: homeplant!
  jwt-expiration-in-ms: 2592000000 # 30일 1000 * 60 * 60 * 24 * 30